name: push

on:
  push:
    branches: [main]

jobs:
  call-build:
    uses: ./.github/workflows/test.yml
  release:
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: yarn

      - run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          title: Publish <version>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
